backend:
  name: git-gateway
local_backend: true

media_folder: "content/images"
public_folder: "../images"

collections:
  - label: "General"
    name: "general"
    editor:
      preview: false
    files:
      - name: "developer"
        label: "Developer profile"
        file: "content/pages/developer.md"
        fields:
          - {
              label: "First name",
              name: "firstName",
              widget: "string",
              pattern: [".{2,20}", "Must have 2-20 characters"],
            }
          - {
              label: "Last name",
              name: "lastName",
              widget: "string",
              pattern: [".{2,20}", "Must have 2-20 characters"],
            }
          - { label: "Avatar image", name: "avatar", widget: "image" }
          - {
              label: "Job position",
              name: "position",
              widget: "string",
              pattern: [".{2,30}", "Must have 2-30 characters"],
            }
          - {
              label: "Phone number",
              name: "phone",
              widget: "string",
              required: false,
            }
          - {
              label: "Email",
              name: "email",
              widget: "string",
              pattern: [".{1,255}", "Must be a valid email address"],
            }
          - {
              label: "City of residence",
              name: "city",
              widget: "string",
              pattern: [".{2,30}", "Must have 2-30 characters"],
            }
          - {
              label: "Country of residence",
              name: "country",
              widget: "string",
              pattern: [".{2,30}", "Must have 2-30 characters"],
            }
          - {
              label: "Available for freelance",
              name: "isFreelancer",
              widget: "boolean",
            }
          - {
              label: "Link to download CV",
              name: "cv",
              widget: "string",
              pattern:
                [
                  'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                  "Must be a valid URL",
                ],
            }
          - label: "Social media"
            name: "socialMedia"
            widget: "object"
            fields:
              - {
                  label: "Twitter profile link",
                  name: "twitter",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
              - {
                  label: "Github profile link",
                  name: "github",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
              - {
                  label: "Instagram profile link",
                  name: "instagram",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
              - {
                  label: "Facebook profile link",
                  name: "facebook",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
      - name: "metadata"
        label: "Site metadata"
        file: "content/pages/metadata.md"
        fields:
          - {
              label: "Page title",
              name: "title",
              widget: "string",
              pattern: [".{5,60}", "Must have 5-60 characters"],
            }
          - {
              label: "Page description",
              name: "description",
              widget: "string",
              pattern: [".{50,160}", "Must have 50-160 characters"],
            }
          - { label: "Page open graph image", name: "image", widget: "image" }
          - {
              label: "Favicon - small icon visible in bookmarks and browser tabs",
              name: "favicon",
              widget: "image",
            }
          - {
              label: "Website language code (ex. 'en', 'pl')",
              name: "language",
              widget: "string",
              pattern:
                ["^[a-z]{2}", "Must have exactly 2 lower-case characters"],
            }
  - label: "Portfolio pages"
    name: "pages"
    editor:
      preview: false
    files:
      - name: "about-me"
        label: "About me"
        file: "content/pages/about-me.md"
        fields:
          - {
              label: "Description",
              name: "description",
              widget: "markdown",
              pattern: [".{100,3000}", "Must have 100-3000 characters"],
            }
          - label: "Skills"
            name: "skills"
            widget: "list"
            fields:
              - {
                  label: "Name",
                  name: "name",
                  widget: "string",
                  pattern: [".{1,50}", "Must have 1-50 characters"],
                }
              - {
                  label: "Category",
                  name: "category",
                  widget: "select",
                  options: ["Technologies", "Tools", "Other"],
                }
              - {
                  label: "Icon",
                  name: "icon",
                  widget: "image",
                  required: false,
                }
              - {
                  label: "Value",
                  name: "value",
                  widget: "number",
                  min: 1,
                  max: 5,
                }
          - label: "Testimonials"
            name: "testimonials"
            widget: list
            required: false
            fields:
              - {
                  label: "Testimonial content",
                  name: "content",
                  widget: "string",
                  pattern: [".{30,160}", "Must have 30-160 characters"],
                }
              - {
                  label: "Testimonial author image",
                  name: "authorImage",
                  widget: "image",
                }
              - {
                  label: "Testimonial author full name",
                  name: "authorName",
                  widget: "string",
                  pattern: [".{5,40}", "Must have 5-40 characters"],
                }
              - {
                  label: "Testimonial author job position",
                  name: "authorJob",
                  widget: "string",
                  pattern: [".{5,40}", "Must have 5-40 characters"],
                }

      - name: "resume"
        label: "Resume"
        file: "content/pages/resume.md"
        fields:
          - label: "Work experience"
            name: "workExperience"
            widget: "list"
            fields:
              - {
                  label: "Job title",
                  name: "jobName",
                  widget: "string",
                  pattern: [".{3,50}", "Must have 3-50 characters"],
                }
              - {
                  label: "Job description",
                  name: "jobDescription",
                  widget: "string",
                  pattern: [".{80,400}", "Must have 80-400 characters"],
                }
              - {
                  label: "Company name",
                  name: "companyName",
                  widget: "string",
                  pattern: [".{3,20}", "Must have 3-20 characters"],
                }
              - { label: "Start date", name: "startDate", widget: "datetime" }
              - { label: "Finish date", name: "finishDate", widget: "datetime" }
          - label: "Education"
            name: "education"
            widget: "list"
            fields:
              - {
                  label: "School/University name",
                  name: "schoolName",
                  widget: "string",
                  pattern: [".{9}", "Must have at least 9 characters"],
                }
              - {
                  label: "Course/Degree",
                  name: "course",
                  widget: "string",
                  pattern: [".{5,100}", "Must have 5-100 characters"],
                }
              - {
                  label: "Education description",
                  name: "description",
                  widget: "string",
                  pattern: [".{80,400}", "Must have 80-400 characters"],
                }
              - { label: "Start date", name: "startDate", widget: "datetime" }
              - { label: "Finish date", name: "finishDate", widget: "datetime" }

      - name: "portfolio"
        label: "Portfolio"
        file: "content/pages/portfolio.md"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - {
                  label: "Project name",
                  name: "name",
                  widget: "string",
                  pattern: [".{5,25}", "Must have 5-25 characters"],
                }
              - {
                  label: "Preview note",
                  name: "previewNote",
                  widget: "string",
                  pattern: [".{5,200}", "Must have 5-200 characters"],
                }
              - {
                  label: "Preview image",
                  name: "previewImage",
                  widget: "image",
                }
              - {
                  label: "Project description",
                  name: "description",
                  widget: "markdown",
                  pattern: [".{5,400}", "Must have 5-400 characters"],
                }
              - {
                  label: "My role in the project",
                  name: "role",
                  widget: "markdown",
                  pattern: [".{10,370}", "Must have 10-370 characters"],
                }
              - {
                  label: "Link to code",
                  name: "code",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
              - {
                  label: "Link to mockups",
                  name: "mockups",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
              - {
                  label: "Link to application",
                  name: "app",
                  widget: "string",
                  required: false,
                  pattern:
                    [
                      'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                      "Must be a valid URL",
                    ],
                }
              - {
                  label: "Project label",
                  name: "label",
                  widget: "select",
                  options: ["Desktop", "Mobile"],
                }
              - {
                  label: "Project start date",
                  name: "startDate",
                  widget: "datetime",
                }
              - {
                  label: "Project finish date",
                  name: "finishDate",
                  widget: "datetime",
                }
              - label: "Technologies"
                name: "technologies"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
